# leak_inspector — record what data a website leaks during a real
# human-driven browsing session.
# Copyright (C) 2026 Jurgen Gaeremyn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Format-specific renderers for :class:`ReportDiff`.

One function per format (HTML, Markdown, Text, JSON); all consume the
same :class:`ReportDiff`. They reuse the per-site reporters' chrome
(BeLibre header, "About this report" intro, capture-status banner) so
the visual identity stays consistent across single-site and diff
reports.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from html import escape as _h
from io import StringIO

from ._branding import (
    BELIBRE_HOMEPAGE,
    belibre_logo_svg_inline,
    BRANDING_TITLE_PREFIX,
)
from .diff import ReportDiff
from .html import (
    _CSS,
    _render_capture_status_banner,
    _render_intro,
)


# --- JSON ------------------------------------------------------------------


def render_diff_json(diff: ReportDiff) -> str:
    """Render a :class:`ReportDiff` as a JSON string.

    Uses :func:`dataclasses.asdict` so every nested dataclass round-trips
    cleanly. ``capture_status_*`` may be ``None`` on the diff; the
    encoder handles that without special-casing.
    """
    return json.dumps(asdict(diff), indent=2, ensure_ascii=False, default=str)


# --- HTML ------------------------------------------------------------------


def render_diff_html(
    diff: ReportDiff,
    *,
    side_report_a: str | None = None,
    side_report_b: str | None = None,
) -> str:
    """Render a :class:`ReportDiff` as a standalone HTML page.

    Reuses the per-site reporters' chrome (BeLibre branding, intro
    disclaimer, capture-status banner CSS) so the visual identity stays
    consistent across single-site and diff reports.

    ``side_report_a`` / ``side_report_b`` are optional relative paths
    to per-side reports written as sibling files (the CLI's ``--out``
    mode produces them). When set, the diff renders a small "Full
    report" link block near the top so the auditor can jump from the
    delta view into the full single-site analysis for either side.
    """
    out = StringIO()
    out.write("<!doctype html>\n")
    out.write('<html lang="en">\n<head>\n<meta charset="utf-8">\n')
    host_label = diff.manifest_b.base_domain or diff.manifest_a.base_domain or "(diff)"
    out.write(
        f"<title>{_h(BRANDING_TITLE_PREFIX)} — Diff: {_h(host_label)} "
        f"({_h(diff.label_a)} → {_h(diff.label_b)})</title>\n"
    )
    out.write(f"<style>{_CSS}{_DIFF_CSS}</style>\n</head>\n<body>\n")

    _render_diff_header(out, diff, host_label)
    _render_intro(out)
    _render_bundle_mismatch(out, diff)
    _render_capture_status_banner(out, diff.capture_status_a)
    _render_capture_status_banner(out, diff.capture_status_b)
    _render_side_report_links_html(
        out, diff, side_report_a, side_report_b,
    )

    _render_diff_headline(out, diff)
    _render_personal_data_delta(out, diff)
    _render_modules_only_in_b(out, diff)
    _render_modules_changed(out, diff)
    _render_modules_only_in_a(out, diff)
    _render_cookie_delta(out, diff)
    _render_storage_delta(out, diff)
    _render_host_delta(out, diff)
    _render_finding_delta(out, diff)
    _render_new_jurisdictions(out, diff)

    out.write(
        "<footer>Generated by leak_inspector — diff "
        f"<code>{_h(diff.label_a)}</code> → <code>{_h(diff.label_b)}</code>"
        f" · session {_h(diff.manifest_a.session_id)} → "
        f"{_h(diff.manifest_b.session_id)}</footer>\n"
    )
    out.write("</body>\n</html>\n")
    return out.getvalue()


_DIFF_CSS = """
header.diff-header h1 { display: flex; align-items: center; gap: 0.5em;
                        flex-wrap: wrap; font-size: 1.4em; }
header.diff-header h1 a { color: inherit; text-decoration: none; }
header.diff-header h1 .belibre-logo { height: 32px; width: auto;
                                       vertical-align: middle; border: none; }
.diff-labels { color: #555; font-size: 0.9em; margin-top: 0.3em; }
.diff-labels code { background: #f4f4f4; padding: 0 0.3em; border-radius: 2px; }

.diff-headline { margin: 1.5em 0 1em; padding: 0.85em 1.25em;
                 background: #fef6f6; border-left: 4px solid #d63138;
                 border-radius: 0 3px 3px 0; font-size: 1.05em;
                 font-weight: 500; color: #842029; }

aside.side-reports { margin: 1em 0; padding: 0.6em 1em;
                     background: #f4f6fb; border-left: 4px solid #4a90c1;
                     border-radius: 0 3px 3px 0; font-size: 0.92em; }
aside.side-reports ul { margin: 0.3em 0 0; padding-left: 1.4em; }
aside.side-reports li { padding: 0.1em 0; }

section.diff-section { margin: 1.5em 0; }
section.diff-section h2 { font-size: 1.1em; margin: 0 0 0.5em;
                          border-bottom: 1px solid #ddd; padding-bottom: 0.2em; }
section.diff-section.added h2 { color: #842029; }
section.diff-section.removed h2 { color: #0f5132; }
section.diff-section.changed h2 { color: #664d03; }

ul.diff-list { list-style: none; padding: 0; margin: 0; }
ul.diff-list li { padding: 0.4em 0.7em; margin: 0.25em 0;
                  border-radius: 0 3px 3px 0;
                  font-size: 0.92em; }
ul.diff-list li.added   { background: #fef6f6; border-left: 3px solid #d63138; }
ul.diff-list li.removed { background: #f3faf6; border-left: 3px solid #0f5132; }
ul.diff-list li.changed { background: #fdf8ee; border-left: 3px solid #b88d2c; }
ul.diff-list li .vendor { color: #555; font-size: 0.88em; }
ul.diff-list li .delta { color: #444; font-size: 0.88em;
                         margin-left: 0.5em; }
.field-added   { color: #842029; }
.field-removed { color: #0f5132; }

table.diff-hosts, table.diff-juris { border-collapse: collapse;
                                     width: 100%; font-size: 0.88em; }
table.diff-hosts th, table.diff-hosts td,
table.diff-juris th, table.diff-juris td { padding: 4px 8px;
                                            text-align: left;
                                            border-bottom: 1px solid #eee;
                                            vertical-align: top; }
table.diff-hosts th, table.diff-juris th { background: #f0f0f0;
                                            font-size: 0.85em; }
"""


def _render_diff_header(out: StringIO, diff: ReportDiff, host_label: str) -> None:
    home = _h(BELIBRE_HOMEPAGE)
    out.write('<header class="diff-header">\n')
    out.write('<h1 class="report-title">\n')
    out.write(
        f'<a class="belibre-link" href="{home}" target="_blank" rel="noopener">'
        f"{belibre_logo_svg_inline()}"
        f"</a>\n"
    )
    out.write(
        f"<span>{_h(BRANDING_TITLE_PREFIX)} — Diff: </span>"
        f"<span>{_h(host_label)}</span>"
    )
    out.write("</h1>\n")
    out.write(
        f'<div class="diff-labels">'
        f"comparing <code>{_h(diff.label_a)}</code>"
        f" → <code>{_h(diff.label_b)}</code>"
        f"</div>\n"
    )
    out.write("</header>\n")


def _render_diff_headline(out: StringIO, diff: ReportDiff) -> None:
    out.write(f'<div class="diff-headline">{_h(diff.headline)}</div>\n')


def _render_modules_only_in_b(out: StringIO, diff: ReportDiff) -> None:
    if not diff.modules_only_in_b:
        return
    out.write('<section class="diff-section added">\n')
    out.write(f"<h2>🆕 New trackers in {_h(diff.label_b)!s}</h2>\n")
    out.write('<ul class="diff-list">\n')
    for m in diff.modules_only_in_b:
        vendor = m.vendor_meta.vendor or ""
        juris = m.vendor_meta.legal_jurisdiction or ""
        juris_part = f" · {_h(juris)}" if juris else ""
        vendor_part = f' <span class="vendor">({_h(vendor)}{juris_part})</span>' if vendor else ""
        out.write(
            f'<li class="added"><strong>{_h(m.module_name)}</strong>'
            f"{vendor_part}</li>\n"
        )
    out.write("</ul>\n</section>\n")


def _render_modules_only_in_a(out: StringIO, diff: ReportDiff) -> None:
    if not diff.modules_only_in_a:
        return
    out.write('<section class="diff-section removed">\n')
    out.write(f"<h2>❌ Trackers no longer firing in {_h(diff.label_b)!s}</h2>\n")
    out.write('<ul class="diff-list">\n')
    for m in diff.modules_only_in_a:
        vendor = m.vendor_meta.vendor or ""
        vendor_part = f' <span class="vendor">({_h(vendor)})</span>' if vendor else ""
        out.write(
            f'<li class="removed"><strong>{_h(m.module_name)}</strong>'
            f"{vendor_part}</li>\n"
        )
    out.write("</ul>\n</section>\n")


def _render_modules_changed(out: StringIO, diff: ReportDiff) -> None:
    if not diff.modules_changed:
        return
    out.write('<section class="diff-section changed">\n')
    out.write("<h2>🔁 Trackers with field-set changes</h2>\n")
    out.write('<ul class="diff-list">\n')
    for c in diff.modules_changed:
        deltas: list[str] = []
        if c.fields_added:
            fields = ", ".join(_h(f) for f in c.fields_added)
            deltas.append(f'<span class="field-added">+{fields}</span>')
        if c.fields_removed:
            fields = ", ".join(_h(f) for f in c.fields_removed)
            deltas.append(f'<span class="field-removed">−{fields}</span>')
        if c.hit_count_a != c.hit_count_b:
            deltas.append(f"hits {c.hit_count_a} → {c.hit_count_b}")
        delta_str = " · ".join(deltas) if deltas else ""
        vendor_part = (
            f' <span class="vendor">({_h(c.vendor)})</span>' if c.vendor else ""
        )
        out.write(
            f'<li class="changed"><strong>{_h(c.module_name)}</strong>'
            f"{vendor_part}"
            f'<span class="delta">{delta_str}</span></li>\n'
        )
    out.write("</ul>\n</section>\n")


def _render_host_delta(out: StringIO, diff: ReportDiff) -> None:
    if not diff.hosts_only_in_a and not diff.hosts_only_in_b:
        return
    out.write('<section class="diff-section">\n')
    out.write("<h2>Third-party host delta</h2>\n")
    out.write('<table class="diff-hosts">\n')
    out.write(
        f"<thead><tr><th>Only in {_h(diff.label_a)}</th>"
        f"<th>Only in {_h(diff.label_b)}</th></tr></thead>\n"
    )
    out.write("<tbody>\n")
    rows = max(len(diff.hosts_only_in_a), len(diff.hosts_only_in_b))
    for i in range(rows):
        a_cell = _h(diff.hosts_only_in_a[i]) if i < len(diff.hosts_only_in_a) else ""
        b_cell = _h(diff.hosts_only_in_b[i]) if i < len(diff.hosts_only_in_b) else ""
        out.write(f"<tr><td><code>{a_cell}</code></td>"
                  f"<td><code>{b_cell}</code></td></tr>\n")
    out.write("</tbody></table>\n</section>\n")


def _render_finding_delta(out: StringIO, diff: ReportDiff) -> None:
    if not diff.findings_only_in_a and not diff.findings_only_in_b:
        return
    out.write('<section class="diff-section">\n')
    out.write("<h2>Finding delta</h2>\n")
    if diff.findings_only_in_b:
        out.write(f"<h3>New in {_h(diff.label_b)}</h3>\n<ul>\n")
        for f in diff.findings_only_in_b:
            out.write(
                f"<li>{f.badge} <strong>{_h(f.headline)}</strong>"
                + (f" — {_h(f.detail)}" if f.detail else "")
                + "</li>\n"
            )
        out.write("</ul>\n")
    if diff.findings_only_in_a:
        out.write(f"<h3>Gone in {_h(diff.label_b)}</h3>\n<ul>\n")
        for f in diff.findings_only_in_a:
            out.write(
                f"<li>{f.badge} <strong>{_h(f.headline)}</strong>"
                + (f" — {_h(f.detail)}" if f.detail else "")
                + "</li>\n"
            )
        out.write("</ul>\n")
    out.write("</section>\n")


def _render_new_jurisdictions(out: StringIO, diff: ReportDiff) -> None:
    if not diff.new_jurisdictions:
        return
    out.write('<section class="diff-section">\n')
    out.write(
        f"<h2>New jurisdictions appearing in {_h(diff.label_b)}</h2>\n"
    )
    out.write(
        "<p>"
        + ", ".join(f"<code>{_h(j)}</code>" for j in diff.new_jurisdictions)
        + "</p>\n"
    )
    out.write("</section>\n")


def _render_bundle_mismatch(out: StringIO, diff: ReportDiff) -> None:
    """Warning banner when A and B don't appear to be the same site."""
    if not diff.bundle_mismatch:
        return
    out.write(
        '<div class="capture-status failure">\n'
        f"<strong>⚠ Bundle mismatch.</strong> {_h(diff.bundle_mismatch)}\n"
        "</div>\n"
    )


def _render_side_report_links_html(
    out: StringIO, diff: ReportDiff,
    side_report_a: str | None, side_report_b: str | None,
) -> None:
    """Links to the per-side single-site reports when ``--out`` produced them."""
    if not side_report_a and not side_report_b:
        return
    out.write('<aside class="side-reports">\n')
    out.write("<strong>Full per-side reports:</strong>\n<ul>\n")
    if side_report_a:
        out.write(
            f'<li><a href="{_h(side_report_a)}">'
            f"{_h(diff.label_a)} — single-site report</a></li>\n"
        )
    if side_report_b:
        out.write(
            f'<li><a href="{_h(side_report_b)}">'
            f"{_h(diff.label_b)} — single-site report</a></li>\n"
        )
    out.write("</ul>\n</aside>\n")


def _render_personal_data_delta(out: StringIO, diff: ReportDiff) -> None:
    """Distinct PII/identifier fields that start or stop leaking between A→B."""
    pdd = diff.personal_data_delta
    if not pdd.only_in_a and not pdd.only_in_b:
        return
    out.write('<section class="diff-section added">\n')
    out.write(
        f"<h2>Personal-data field delta "
        f"({_h(diff.label_a)} {pdd.count_a} → {_h(diff.label_b)} {pdd.count_b})</h2>\n"
    )
    if pdd.only_in_b:
        out.write(f"<h3>New in <code>{_h(diff.label_b)}</code></h3>\n")
        out.write('<ul class="diff-list">\n')
        for f in pdd.only_in_b:
            out.write(
                f'<li class="added"><b>{_h(f.vendor)}</b>'
                f' <span class="vendor">({_h(f.category)})</span>'
                f' <code>{_h(f.key)}</code></li>\n'
            )
        out.write("</ul>\n")
    if pdd.only_in_a:
        out.write(f"<h3>Only in <code>{_h(diff.label_a)}</code></h3>\n")
        out.write('<ul class="diff-list">\n')
        for f in pdd.only_in_a:
            out.write(
                f'<li class="removed"><b>{_h(f.vendor)}</b>'
                f' <span class="vendor">({_h(f.category)})</span>'
                f' <code>{_h(f.key)}</code></li>\n'
            )
        out.write("</ul>\n")
    out.write("</section>\n")


def _render_cookie_delta(out: StringIO, diff: ReportDiff) -> None:
    """Cookies present in one capture but not the other (matched by name+host)."""
    if not diff.cookies_added and not diff.cookies_removed:
        return
    out.write('<section class="diff-section">\n')
    out.write("<h2>Cookie delta</h2>\n")
    if diff.cookies_added:
        out.write(f"<h3>New in <code>{_h(diff.label_b)}</code></h3>\n")
        out.write('<ul class="diff-list">\n')
        for c in diff.cookies_added:
            party = "1P" if c.is_first_party else "3P"
            out.write(
                f'<li class="added"><code>{_h(c.name)}</code>'
                f' <span class="vendor">@ {_h(c.host)}</span>'
                f' [{party}, {_h(c.lifetime_human)}]</li>\n'
            )
        out.write("</ul>\n")
    if diff.cookies_removed:
        out.write(f"<h3>Only in <code>{_h(diff.label_a)}</code></h3>\n")
        out.write('<ul class="diff-list">\n')
        for c in diff.cookies_removed:
            party = "1P" if c.is_first_party else "3P"
            out.write(
                f'<li class="removed"><code>{_h(c.name)}</code>'
                f' <span class="vendor">@ {_h(c.host)}</span>'
                f' [{party}, {_h(c.lifetime_human)}]</li>\n'
            )
        out.write("</ul>\n")
    out.write("</section>\n")


def _render_storage_delta(out: StringIO, diff: ReportDiff) -> None:
    """``localStorage``/``sessionStorage`` keys present on one side only."""
    if not diff.storage_added and not diff.storage_removed:
        return
    out.write('<section class="diff-section">\n')
    out.write("<h2>Browser-storage delta</h2>\n")
    if diff.storage_added:
        out.write(f"<h3>New in <code>{_h(diff.label_b)}</code></h3>\n")
        out.write('<ul class="diff-list">\n')
        for s in diff.storage_added:
            out.write(
                f'<li class="added">[{_h(s.kind)}] <code>{_h(s.key)}</code>'
                f' <span class="vendor">@ {_h(s.origin)}</span></li>\n'
            )
        out.write("</ul>\n")
    if diff.storage_removed:
        out.write(f"<h3>Only in <code>{_h(diff.label_a)}</code></h3>\n")
        out.write('<ul class="diff-list">\n')
        for s in diff.storage_removed:
            out.write(
                f'<li class="removed">[{_h(s.kind)}] <code>{_h(s.key)}</code>'
                f' <span class="vendor">@ {_h(s.origin)}</span></li>\n'
            )
        out.write("</ul>\n")
    out.write("</section>\n")


# --- Markdown --------------------------------------------------------------


def render_diff_markdown(
    diff: ReportDiff,
    *,
    side_report_a: str | None = None,
    side_report_b: str | None = None,
) -> str:
    """Render a :class:`ReportDiff` as a Markdown document.

    Mirrors the HTML structure (header, intro, headline, delta sections)
    using plain markdown — no inline HTML except links. Suitable for
    git-friendly artifacts, pandoc pipelines, and GitHub previews.

    ``side_report_a`` / ``side_report_b`` are optional relative paths
    to per-side reports. When set, "Full per-side reports" links appear
    near the top of the diff.
    """
    from .markdown import _render_capture_status_banner as md_capture_banner
    from .markdown import _render_intro as md_intro

    out = StringIO()
    host_label = diff.manifest_b.base_domain or diff.manifest_a.base_domain or "(diff)"
    out.write(
        f"# {BRANDING_TITLE_PREFIX} — Diff: {host_label}\n\n"
    )
    out.write(f"comparing `{diff.label_a}` → `{diff.label_b}`\n\n")

    md_intro(out)
    if diff.bundle_mismatch:
        out.write(f"> ⚠ **Bundle mismatch.** {diff.bundle_mismatch}\n\n")
    md_capture_banner(out, diff.capture_status_a)
    md_capture_banner(out, diff.capture_status_b)

    if side_report_a or side_report_b:
        out.write("**Full per-side reports:**\n\n")
        if side_report_a:
            out.write(
                f"- [`{diff.label_a}` — single-site report]({side_report_a})\n"
            )
        if side_report_b:
            out.write(
                f"- [`{diff.label_b}` — single-site report]({side_report_b})\n"
            )
        out.write("\n")

    out.write(f"> **{diff.headline}**\n\n")

    pdd = diff.personal_data_delta
    if pdd.only_in_a or pdd.only_in_b:
        out.write(
            f"## Personal-data field delta "
            f"(`{diff.label_a}` {pdd.count_a} → `{diff.label_b}` {pdd.count_b})\n\n"
        )
        if pdd.only_in_b:
            out.write(f"### New in `{diff.label_b}`\n\n")
            for f in pdd.only_in_b:
                out.write(f"- **{f.vendor}** ({f.category}) `{f.key}`\n")
            out.write("\n")
        if pdd.only_in_a:
            out.write(f"### Only in `{diff.label_a}`\n\n")
            for f in pdd.only_in_a:
                out.write(f"- **{f.vendor}** ({f.category}) `{f.key}`\n")
            out.write("\n")

    if diff.modules_only_in_b:
        out.write(f"## 🆕 New trackers in `{diff.label_b}`\n\n")
        for m in diff.modules_only_in_b:
            vendor = m.vendor_meta.vendor or ""
            juris = m.vendor_meta.legal_jurisdiction or ""
            extras = []
            if vendor:
                extras.append(vendor)
            if juris:
                extras.append(juris)
            tail = f" *({' · '.join(extras)})*" if extras else ""
            out.write(f"- **{m.module_name}**{tail}\n")
        out.write("\n")

    if diff.modules_changed:
        out.write("## 🔁 Trackers with field-set changes\n\n")
        for c in diff.modules_changed:
            vendor = f" *({c.vendor})*" if c.vendor else ""
            out.write(f"- **{c.module_name}**{vendor}\n")
            if c.fields_added:
                out.write(f"  - `+{', '.join(c.fields_added)}`\n")
            if c.fields_removed:
                out.write(f"  - `−{', '.join(c.fields_removed)}`\n")
            if c.hit_count_a != c.hit_count_b:
                out.write(f"  - hits: {c.hit_count_a} → {c.hit_count_b}\n")
        out.write("\n")

    if diff.modules_only_in_a:
        out.write(f"## ❌ Trackers no longer firing in `{diff.label_b}`\n\n")
        for m in diff.modules_only_in_a:
            vendor = f" *({m.vendor_meta.vendor})*" if m.vendor_meta.vendor else ""
            out.write(f"- **{m.module_name}**{vendor}\n")
        out.write("\n")

    if diff.cookies_added or diff.cookies_removed:
        out.write("## Cookie delta\n\n")
        if diff.cookies_added:
            out.write(f"### New in `{diff.label_b}`\n\n")
            for c in diff.cookies_added:
                party = "1P" if c.is_first_party else "3P"
                out.write(
                    f"- `{c.name}` @ `{c.host}` "
                    f"[{party}, {c.lifetime_human}]\n"
                )
            out.write("\n")
        if diff.cookies_removed:
            out.write(f"### Only in `{diff.label_a}`\n\n")
            for c in diff.cookies_removed:
                party = "1P" if c.is_first_party else "3P"
                out.write(
                    f"- `{c.name}` @ `{c.host}` "
                    f"[{party}, {c.lifetime_human}]\n"
                )
            out.write("\n")

    if diff.storage_added or diff.storage_removed:
        out.write("## Browser-storage delta\n\n")
        if diff.storage_added:
            out.write(f"### New in `{diff.label_b}`\n\n")
            for s in diff.storage_added:
                out.write(f"- [{s.kind}] `{s.key}` @ `{s.origin}`\n")
            out.write("\n")
        if diff.storage_removed:
            out.write(f"### Only in `{diff.label_a}`\n\n")
            for s in diff.storage_removed:
                out.write(f"- [{s.kind}] `{s.key}` @ `{s.origin}`\n")
            out.write("\n")

    if diff.hosts_only_in_a or diff.hosts_only_in_b:
        out.write("## Third-party host delta\n\n")
        if diff.hosts_only_in_b:
            out.write(f"### Only in `{diff.label_b}`\n\n")
            for h in diff.hosts_only_in_b:
                out.write(f"- `{h}`\n")
            out.write("\n")
        if diff.hosts_only_in_a:
            out.write(f"### Only in `{diff.label_a}`\n\n")
            for h in diff.hosts_only_in_a:
                out.write(f"- `{h}`\n")
            out.write("\n")

    if diff.findings_only_in_a or diff.findings_only_in_b:
        out.write("## Finding delta\n\n")
        if diff.findings_only_in_b:
            out.write(f"### New in `{diff.label_b}`\n\n")
            for f in diff.findings_only_in_b:
                detail = f" — {f.detail}" if f.detail else ""
                out.write(f"- {f.badge} **{f.headline}**{detail}\n")
            out.write("\n")
        if diff.findings_only_in_a:
            out.write(f"### Gone in `{diff.label_b}`\n\n")
            for f in diff.findings_only_in_a:
                detail = f" — {f.detail}" if f.detail else ""
                out.write(f"- {f.badge} **{f.headline}**{detail}\n")
            out.write("\n")

    if diff.new_jurisdictions:
        out.write(f"## New jurisdictions in `{diff.label_b}`\n\n")
        out.write(", ".join(f"`{j}`" for j in diff.new_jurisdictions) + "\n\n")

    return out.getvalue()


# --- Text ------------------------------------------------------------------


def render_diff_text(
    diff: ReportDiff,
    *,
    color: bool = True,
    side_report_a: str | None = None,
    side_report_b: str | None = None,
) -> str:
    """Render a :class:`ReportDiff` as plain text for terminal display.

    Reuses the existing text reporter's palette for bold / section
    headers / impact colours so the look matches single-site reports.
    Set ``color=False`` to suppress all ANSI escapes (useful for
    piping into less / grep, and for tests).

    ``side_report_a`` / ``side_report_b`` are optional relative paths
    surfaced near the top so the operator knows where to find each
    side's full single-site report.
    """
    from .text import _Palette, _write_capture_status_banner, _write_intro

    p = _Palette(color)
    out = StringIO()
    host_label = diff.manifest_b.base_domain or diff.manifest_a.base_domain or "(diff)"

    bar = "=" * 78
    out.write(f"{bar}\n")
    out.write(p.header(f"{BRANDING_TITLE_PREFIX} — Diff: {host_label}") + "\n")
    out.write(p.dim(f"comparing:  {diff.label_a}  →  {diff.label_b}") + "\n")
    out.write(p.dim(f"sessions:   {diff.manifest_a.session_id}  →  "
                    f"{diff.manifest_b.session_id}") + "\n")
    out.write(f"{bar}\n\n")

    _write_intro(out, p)
    if diff.bundle_mismatch:
        out.write(p.impact("high", f"⚠ Bundle mismatch: {diff.bundle_mismatch}") + "\n\n")
    _write_capture_status_banner(out, diff.capture_status_a, p)
    _write_capture_status_banner(out, diff.capture_status_b, p)

    if side_report_a or side_report_b:
        out.write(p.header("Full per-side reports:") + "\n")
        if side_report_a:
            out.write(f"  {diff.label_a}: {side_report_a}\n")
        if side_report_b:
            out.write(f"  {diff.label_b}: {side_report_b}\n")
        out.write("\n")

    out.write(p.header(diff.headline) + "\n")
    out.write("─" * 78 + "\n\n")

    pdd = diff.personal_data_delta
    if pdd.only_in_a or pdd.only_in_b:
        out.write(p.section(
            f"Personal-data field delta "
            f"({diff.label_a} {pdd.count_a} → {diff.label_b} {pdd.count_b})"
        ) + "\n")
        out.write("─" * 78 + "\n")
        if pdd.only_in_b:
            out.write(p.dim(f"  New in {diff.label_b}:") + "\n")
            for f in pdd.only_in_b:
                out.write(f"    + {f.vendor}  ({f.category})  {f.key}\n")
        if pdd.only_in_a:
            out.write(p.dim(f"  Only in {diff.label_a}:") + "\n")
            for f in pdd.only_in_a:
                out.write(f"    - {f.vendor}  ({f.category})  {f.key}\n")
        out.write("\n")

    if diff.modules_only_in_b:
        out.write(p.section(f"New trackers in {diff.label_b}") + "\n")
        out.write("─" * 78 + "\n")
        for m in diff.modules_only_in_b:
            vendor = m.vendor_meta.vendor or ""
            juris = m.vendor_meta.legal_jurisdiction or ""
            extras = " · ".join([x for x in (vendor, juris) if x])
            tail = f"  ({extras})" if extras else ""
            out.write(f"  + {m.module_name}{tail}\n")
        out.write("\n")

    if diff.modules_changed:
        out.write(p.section("Trackers with field-set changes") + "\n")
        out.write("─" * 78 + "\n")
        for c in diff.modules_changed:
            vendor = f"  ({c.vendor})" if c.vendor else ""
            out.write(f"  ~ {c.module_name}{vendor}\n")
            if c.fields_added:
                out.write(p.dim(f"      added:   +{', '.join(c.fields_added)}") + "\n")
            if c.fields_removed:
                out.write(p.dim(f"      removed: -{', '.join(c.fields_removed)}") + "\n")
            if c.hit_count_a != c.hit_count_b:
                out.write(p.dim(f"      hits:    {c.hit_count_a} -> {c.hit_count_b}") + "\n")
        out.write("\n")

    if diff.modules_only_in_a:
        out.write(p.section(f"Trackers no longer firing in {diff.label_b}") + "\n")
        out.write("─" * 78 + "\n")
        for m in diff.modules_only_in_a:
            vendor = f"  ({m.vendor_meta.vendor})" if m.vendor_meta.vendor else ""
            out.write(f"  - {m.module_name}{vendor}\n")
        out.write("\n")

    if diff.cookies_added or diff.cookies_removed:
        out.write(p.section("Cookie delta") + "\n")
        out.write("─" * 78 + "\n")
        if diff.cookies_added:
            out.write(p.dim(f"  New in {diff.label_b}:") + "\n")
            for c in diff.cookies_added:
                party = "1P" if c.is_first_party else "3P"
                out.write(
                    f"    + {c.name:<28} @ {c.host}  "
                    f"[{party}, {c.lifetime_human}]\n"
                )
        if diff.cookies_removed:
            out.write(p.dim(f"  Only in {diff.label_a}:") + "\n")
            for c in diff.cookies_removed:
                party = "1P" if c.is_first_party else "3P"
                out.write(
                    f"    - {c.name:<28} @ {c.host}  "
                    f"[{party}, {c.lifetime_human}]\n"
                )
        out.write("\n")

    if diff.storage_added or diff.storage_removed:
        out.write(p.section("Browser-storage delta") + "\n")
        out.write("─" * 78 + "\n")
        if diff.storage_added:
            out.write(p.dim(f"  New in {diff.label_b}:") + "\n")
            for s in diff.storage_added:
                out.write(f"    + [{s.kind}] {s.key}  @ {s.origin}\n")
        if diff.storage_removed:
            out.write(p.dim(f"  Only in {diff.label_a}:") + "\n")
            for s in diff.storage_removed:
                out.write(f"    - [{s.kind}] {s.key}  @ {s.origin}\n")
        out.write("\n")

    if diff.hosts_only_in_a or diff.hosts_only_in_b:
        out.write(p.section("Third-party host delta") + "\n")
        out.write("─" * 78 + "\n")
        if diff.hosts_only_in_b:
            out.write(p.dim(f"  Only in {diff.label_b}:") + "\n")
            for h in diff.hosts_only_in_b:
                out.write(f"    + {h}\n")
        if diff.hosts_only_in_a:
            out.write(p.dim(f"  Only in {diff.label_a}:") + "\n")
            for h in diff.hosts_only_in_a:
                out.write(f"    - {h}\n")
        out.write("\n")

    if diff.findings_only_in_a or diff.findings_only_in_b:
        out.write(p.section("Finding delta") + "\n")
        out.write("─" * 78 + "\n")
        for f in diff.findings_only_in_b:
            detail = f"  — {f.detail}" if f.detail else ""
            out.write(f"  + {f.badge} {f.headline}{detail}\n")
        for f in diff.findings_only_in_a:
            detail = f"  — {f.detail}" if f.detail else ""
            out.write(f"  - {f.badge} {f.headline}{detail}\n")
        out.write("\n")

    if diff.new_jurisdictions:
        out.write(p.section(f"New jurisdictions in {diff.label_b}") + "\n")
        out.write("─" * 78 + "\n")
        out.write("  " + ", ".join(diff.new_jurisdictions) + "\n\n")

    return out.getvalue()


__all__ = [
    "render_diff_html",
    "render_diff_json",
    "render_diff_markdown",
    "render_diff_text",
]
